# https://circleci.com/docs/2.0/configuration-reference/
aliases:
  - &init-gcloud |
    echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
    gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
    gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
version: 2.1
orbs:
  win: circleci/windows@2.1.0
jobs:
  integration:
    environment:
      OKTETO_USER: cindylopez
    docker:
      - image: okteto/dev:go1.17
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - 14:34:10:32:01:82:71:b8:69:76:8e:56:dd:10:fc:13
            - a5:c2:c7:93:ee:7b:5f:11:a4:77:2c:c9:f1:e5:b0:e4
      - restore_cache:
          keys:
            - v4-pkg-cache-{{ checksum "go.sum" }}
      - attach_workspace:
          at: ./artifacts
      - run:
          command: go mod tidy && git diff --exit-code go.sum > /dev/null
      - run:
          name: Prepare env
          command: |            
            git clone https://github.com/okteto/installer.git ~/installer
            git clone https://github.com/okteto/app.git ~/app
            cp ~/installer/gcp/examples/integration/* ~/installer/gcp/
            export TF_VAR_oktetoConfig='{
                      chart = "/~/app/chart/okteto-enterprise"
                      version = "0.10.4"
                        }'
      - run:
          name: Integration tests
          environment:
            OKTETO_SKIP_CLEANUP: 'true'
            NAME: 'integratione2e'
            URL_INSTALLER: '~/installer/gcp'            
          command: make integration
      - save_cache:
          key: v4-pkg-cache-{{ checksum "go.sum" }}
          paths:
            - ~/.cache/go-build
            - /go/pkg
      - store_artifacts:
          path: /root/.okteto

workflows:
  version: 2
  build-release:
    jobs:
      - integration:          
          filters:
            branches:
              only:
                - /^mario.*/
      